stock_screening_portfolio:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: clean_stock_data
      threads: 4
      keyfile: /opt/airflow/dags/credentials/bq_key.json
      location: US