stock_screening_portfolio:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: daily-stock-monitoring
      dataset: clean_stock_data
      threads: 4
      keyfile: /opt/airflow/dags/credentials/bq_key.json
      timeout_seconds: 300
      location: US